(() => {
  const CLASS_META = {
    stationary:{label:"Stationary",color:"var(--stationary)",count:"count-stationary"},
    low_vibration:{label:"Low vibration",color:"var(--low)",count:"count-low"},
    high_vibration:{label:"High vibration",color:"var(--high)",count:"count-high"},
    inference:{label:"Inference label",color:"var(--faint)"}
  };
  const classFromValue = {0:"stationary",1:"low_vibration",2:"high_vibration"};
  const state = {port:null,reader:null,readTask:null,keepReading:false,phase:"disconnected",lineBuffer:"",activeRecord:null,records:[],counts:{stationary:0,low_vibration:0,high_vibration:0}};
  const $ = id => document.getElementById(id);
  const els = {dot:$("status-dot"),status:$("status-text"),recordDot:$("record-dot"),recordStatus:$("record-status"),error:$("serial-error"),record:$("record"),stop:$("stop"),inference:$("inference"),classSelect:$("record-class"),heroIcon:$("hero-icon"),heroLabel:$("hero-label"),heroConf:$("hero-conf"),heroTime:$("hero-time"),heroSource:$("hero-source"),bar:$("confidence-bar"),detections:$("detection-rows"),emptyDetections:$("empty-detections"),records:$("record-list"),emptyRecords:$("empty-records")};
  const setStatus = (kind,text) => { els.dot.className = "dot" + (kind ? " " + kind : ""); els.status.textContent = text; };
  const showError = text => { els.error.textContent = text; els.error.style.display = "block"; };
  const hideError = () => { els.error.style.display = "none"; };
  const displayClass = key => CLASS_META[key]?.label || "Unknown";
  const formatTime = date => date.toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit",second:"2-digit"});
  const setRecordStatus = (text,live=false) => { els.recordStatus.textContent=text; els.recordDot.className="dot"+(live?" live":""); };
  const updateControls = () => { const connected=!!state.port; const ready=connected && state.phase==="ready"; const active=state.phase==="recording" || state.phase==="inference"; els.record.disabled=!ready; els.inference.disabled=!ready; els.stop.disabled=!active; $("connect").disabled=connected; $("disconnect").disabled=!connected; };
  const send = async text => { if(!state.port?.writable) throw new Error("The serial port is not writable."); const writer=state.port.writable.getWriter(); try{ await writer.write(new TextEncoder().encode(text)); } finally { writer.releaseLock(); } };
  const updateHero = (key,confidence,source) => { const meta=CLASS_META[key] || {label:"Unknown",color:"var(--faint)"}; const value=confidence===null?null:Math.max(0,Math.min(1,confidence)); els.heroLabel.textContent=meta.label; els.heroIcon.style.color=meta.color; els.heroConf.textContent=value===null?"—":Math.round(value*100)+"%"; els.heroTime.textContent=formatTime(new Date()); els.heroSource.textContent=source; els.bar.style.width=value===null?"0%":Math.round(value*100)+"%"; els.bar.style.background=meta.color; };
  const addDetection = (key,confidence) => { const meta=CLASS_META[key]; if(!meta)return; state.counts[key]++; $(meta.count).textContent=state.counts[key]; els.emptyDetections.style.display="none"; const row=document.createElement("tr"); [formatTime(new Date()),meta.label,confidence===null?"—":Math.round(confidence*100)+"%"].forEach((value,index)=>{const cell=document.createElement("td"); cell.textContent=value; if(index===1)cell.className="tag"; row.appendChild(cell);}); els.detections.prepend(row); };
  const handleInference = data => { const key=data.class; const confidence=typeof data.confidence==="number"?data.confidence:null; updateHero(key,confidence,"USB serial"); addDetection(key,confidence); };
  const finishRecord = () => { const record=state.activeRecord; if(!record)return; record.completedAt=new Date(); record.csv=[record.header,...record.rows].filter(Boolean).join("\r\n")+"\r\n"; state.records.unshift(record); state.activeRecord=null; state.phase="ready"; setRecordStatus("Ready for another session"); renderRecords(); updateControls(); };
  const handleCsvLine = line => { if(!state.activeRecord)return; if(!state.activeRecord.header && line.startsWith("label,class_name,")){state.activeRecord.header=line;return;} if(state.activeRecord.header && /^[0-2],/.test(line)){state.activeRecord.rows.push(line); setRecordStatus("Recording · "+state.activeRecord.rows.length+" rows",true); } };
  const handleLine = line => { if(!line)return; if(line.startsWith("# calibration_samples=")){state.phase="calibrating";setRecordStatus("Calibrating");setStatus(null,"Calibrating · keep sensor still");updateControls();return;} if(line==="# calibration_done"){state.phase="ready";setRecordStatus("Ready after calibration");setStatus(null,"Calibration complete · choose a mode");updateControls();return;} if(line==="# mode_prompt"){state.phase="ready";setRecordStatus("Ready for a mode");setStatus(null,"Connected · choose a mode");updateControls();return;} if(line==="# class_prompt"){setRecordStatus("Choose a dataset class");return;} if(line.startsWith("# record_start,")){const match=line.match(/session_id=(\d+),class_name=([^\s]+)/); state.activeRecord={id:match?match[1]:String(Date.now()),className:match?match[2]:classFromValue[els.classSelect.value],startedAt:new Date(),header:"",rows:[]};state.phase="recording";setRecordStatus("Recording · 0 rows",true);setStatus("live","Recording session active");updateControls();return;} if(line.startsWith("# record_stop")){finishRecord();setStatus("live","Session saved");return;} if(line.startsWith("# inference_ready")){state.phase="inference";setRecordStatus("Inference active");setStatus("live","Inference active");updateControls();return;} if(line.startsWith("# inference_stop")){state.phase="ready";setRecordStatus("Ready for another session");updateControls();return;} if(line.startsWith("{")){try{handleInference(JSON.parse(line));}catch(_){ }return;} handleCsvLine(line); };
  const readSerial = async port => { const decoder=new TextDecoderStream(); const pipe=port.readable.pipeTo(decoder.writable).catch(()=>{}); const reader=decoder.readable.getReader(); state.reader=reader; try{while(state.keepReading){const {value,done}=await reader.read();if(done)break;if(value){state.lineBuffer+=value;let index;while((index=state.lineBuffer.indexOf("\n"))>=0){const line=state.lineBuffer.slice(0,index).replace(/\r$/i,"").trim();state.lineBuffer=state.lineBuffer.slice(index+1);handleLine(line);}}}}catch(error){if(state.keepReading)showError("Serial read failed: "+error.message);}finally{reader.releaseLock();await pipe;state.reader=null;} };
  const connect = async () => { hideError(); if(!("serial" in navigator)){showError("Web Serial is unavailable. Use current Chrome or Edge.");return;} try{const port=await navigator.serial.requestPort();await port.open({baudRate:Number($("baud").value)});state.port=port;state.keepReading=true;state.phase="calibrating";setStatus(null,"Connected · waiting for calibration");setRecordStatus("Waiting for calibration");updateControls();state.readTask=readSerial(port);port.addEventListener?.("disconnect",()=>disconnect("USB cable disconnected"));}catch(error){showError("Could not open serial port: "+error.message);} };
  const disconnect = async message => { state.keepReading=false;try{await state.reader?.cancel();}catch(_){}try{await state.readTask;}catch(_){}try{await state.port?.close();}catch(_){}state.port=null;state.reader=null;state.readTask=null;state.phase="disconnected";state.activeRecord=null;setStatus(null,message||"Disconnected");setRecordStatus("Ready after calibration");updateControls(); };
  const renderRecords = () => { els.records.querySelectorAll(".record-item").forEach(node=>node.remove());els.emptyRecords.style.display=state.records.length?"none":"block";state.records.forEach(record=>{const item=document.createElement("article");item.className="record-item";const info=document.createElement("div");const title=document.createElement("h3");title.textContent=displayClass(record.className);const meta=document.createElement("div");meta.className="record-meta";meta.innerHTML="<span>Session <strong>"+record.id+"</strong></span><span>Rows <strong>"+record.rows.length+"</strong></span><span>"+record.completedAt.toLocaleString()+"</span>";info.append(title,meta);const actions=document.createElement("div");actions.className="record-actions";const download=document.createElement("button");download.className="btn small";download.textContent="Download CSV";download.onclick=()=>{const blob=new Blob([record.csv],{type:"text/csv;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="vibeflow-session-"+record.id+".csv";link.click();URL.revokeObjectURL(link.href);};const remove=document.createElement("button");remove.className="btn small danger";remove.textContent="Delete";remove.onclick=()=>{state.records=state.records.filter(item=>item!==record);renderRecords();};actions.append(download,remove);item.append(info,actions);els.records.appendChild(item);}); };
  $("connect").onclick=connect;$("disconnect").onclick=()=>disconnect();$("record").onclick=async()=>{try{await send("r");setRecordStatus("Choose a dataset class");state.phase="class_selection";updateControls();setTimeout(async()=>{if(state.phase==="class_selection"){const command=els.classSelect.value==="inference"?"3":els.classSelect.value;await send(command);}},50);}catch(error){showError(error.message);}};$("stop").onclick=async()=>{try{await send("s");}catch(error){showError(error.message);}};$("inference").onclick=async()=>{try{await send("i");state.phase="inference_starting";updateControls();}catch(error){showError(error.message);}};$("clear-detections").onclick=()=>{els.detections.innerHTML="";els.emptyDetections.style.display="block";state.counts={stationary:0,low_vibration:0,high_vibration:0};Object.values(CLASS_META).forEach(meta=>$(meta.count).textContent="0");};$("clear-records").onclick=()=>{state.records=[];renderRecords();};if("serial" in navigator)navigator.serial.addEventListener("disconnect",event=>{if(event.target===state.port)disconnect("USB cable disconnected")});updateControls();renderRecords();
})();
